# Generated by Django 4.0.2 on 2022-02-23 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pets_project.pet_app.helpers_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('bunny', 'bunny'), ('parrot', 'parrot'), ('fish', 'fish'), ('other', 'other')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), pets_project.pet_app.helpers_functions.has_letters_only_validator])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), pets_project.pet_app.helpers_functions.has_letters_only_validator])),
                ('picture', models.URLField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('do not show', 'do not show')], default='do not show', max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True)),
                ('photo', models.ImageField(upload_to='', validators=[pets_project.pet_app.helpers_functions.validate_file_size])),
                ('description', models.TextField(blank=True, null=True)),
                ('likes', models.ImageField(default=0, upload_to='')),
                ('tagged_pets', models.ManyToManyField(to='pet_app.Pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together={('owner', 'name')},
        ),
    ]
