# Generated by Django 4.0.2 on 2022-02-24 09:02

from django.db import migrations, models
import pets_project.pet_app.helpers_functions


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='photos', validators=[pets_project.pet_app.helpers_functions.validate_file_size]),
        ),
    ]
