# Generated by Django 4.0.2 on 2022-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0003_alter_petphoto_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
